// import './datatype'
// import './enum'
// import './interface'
// import './function'
// import './class'
// import './class-interface'
// import './generics'
// import './advance'
// import './m'
import './es6/c'

